insert into `optionitem` (`id`, `type`, `name`) VALUES (0, 0, 'Tấn công+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (1, 0, 'Thời gian sử dụng # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (2, 0, 'HP, KI+#000');
insert into `optionitem` (`id`, `type`, `name`) VALUES (3, 0, 'Vô hiệu và biến #% sát thương chưởng thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (4, 0, 'Hồi phục #% KI khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (5, 0, '+#% sát thương chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (6, 0, 'HP+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (7, 0, 'KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (8, 0, 'Hút #% HP, KI xung quanh mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (9, 0, 'Hiệu lực trong # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (10, 0, 'Chính xác: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (11, 0, 'Công đức +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (12, 0, 'Số lần sử dụng còn lại +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (13, 0, 'Số yêu quái đã hạ +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (14, 0, 'Chí mạng+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (15, 0, 'Phản đòn cận chiến+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (16, 0, 'Tốc độ di chuyển+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (17, 0, 'Né đòn: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (18, 0, 'Chính xác: +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (19, 0, 'Tấn công+#% khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (20, 0, 'PIN #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (21, 0, 'Yêu cầu sức mạnh # tỉ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (22, 0, 'HP+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (23, 0, 'KI+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (24, 0, 'Làm tăng trọng lực, gây chậm mọi người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (25, 0, 'Tàng hình mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (26, 0, 'Hóa đá mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (27, 0, '+# HP/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (28, 0, '+# KI/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (29, 0, 'Biến Sôcôla mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (30, 0, 'Không thể giao dịch');
insert into `optionitem` (`id`, `type`, `name`) VALUES (31, 0, 'Số lượng #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (32, 0, 'Không bị hóa Xương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (33, 0, 'Dịch chuyển tức thời');
insert into `optionitem` (`id`, `type`, `name`) VALUES (34, 0, 'Tinh ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (35, 0, 'Nguyệt ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (36, 0, 'Nhật ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (37, 0, 'Số lần đã ký gửi #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (38, 0, 'Chỉ có tác dụng khi hợp thể');
insert into `optionitem` (`id`, `type`, `name`) VALUES (39, 0, '<Cập nhật bản mới để xem>');
insert into `optionitem` (`id`, `type`, `name`) VALUES (40, 0, 'Siêu cải trang # đá ngũ sắc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (41, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (42, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (43, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (44, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (45, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (46, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (47, 0, 'Giáp+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (48, 0, 'HP, KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (49, 0, 'Tấn công+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (50, 0, 'Sức đánh+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (51, 0, 'Sôn Gô Ku ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (52, 0, 'Ca Đic siêu ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (53, 0, 'Broly');
insert into `optionitem` (`id`, `type`, `name`) VALUES (54, 0, 'Mr. Santa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (55, 0, 'Broly ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (56, 0, 'Ca Lích');
insert into `optionitem` (`id`, `type`, `name`) VALUES (57, 0, 'Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (58, 0, 'Pic');
insert into `optionitem` (`id`, `type`, `name`) VALUES (59, 0, 'Siêu na mếc #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (60, 0, 'Sôn Gô Tên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (61, 0, 'Sôn Gô Ku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (62, 0, 'Phục hồi thể lực #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (63, 0, 'Còn lại # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (64, 0, 'Còn lại # giờ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (65, 0, 'Còn lại # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (66, 0, 'Chưa có');
insert into `optionitem` (`id`, `type`, `name`) VALUES (67, 0, 'Dùng nâng cấp găng tay');
insert into `optionitem` (`id`, `type`, `name`) VALUES (68, 0, 'Dùng để nâng cấp áo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (69, 0, 'Dùng để nâng cấp quần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (70, 0, 'Dùng để nâng cấp giày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (71, 0, 'HS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (72, 0, 'Cấp #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (73, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (74, 0, 'Dùng để ép thành đá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (75, 0, 'Dùng để làm phép');
insert into `optionitem` (`id`, `type`, `name`) VALUES (76, 0, 'Vip');
insert into `optionitem` (`id`, `type`, `name`) VALUES (77, 0, 'HP+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (78, 0, 'Sức hủy diệt+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (79, 0, 'Đệ tử #% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (80, 0, 'HP+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (81, 0, 'KI+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (82, 0, 'Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (83, 0, 'Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (84, 0, 'Dùng để bay không tốn KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (85, 0, 'Dùng để bay và phục hồi KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (86, 0, 'Ký gửi vàng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (87, 0, 'Ký gửi ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (88, 0, 'Cộng #% exp khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (89, 0, 'Dùng để bay và phục hồi HP, KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (90, 0, 'Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (91, 0, 'Mở ra để nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (92, 0, 'Chúc tết bang hội và mọi người kèm theo pháo hoa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (93, 0, 'HSD # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (94, 0, 'Giáp #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (95, 0, 'Biến #% tấn công thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (96, 0, 'Biến #% tấn công thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (97, 0, 'Phản #% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (98, 0, 'Xuyên giáp #% chưởng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (99, 0, 'Xuyên giáp #% cận chiến');
insert into `optionitem` (`id`, `type`, `name`) VALUES (100, 0, '+#% vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (101, 0, '+#% TN,SM');
insert into `optionitem` (`id`, `type`, `name`) VALUES (102, 0, '# Sao Pha Lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (103, 0, 'KI +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (104, 0, 'Biến #% tấn công quái thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (105, 0, 'Vô hình khi không đánh quái và boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (106, 0, 'Không ảnh hưởng bởi cái lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (107, 0, '# Sao Pha Lê (Chưa ép)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (108, 0, '#% Né đòn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (109, 0, 'Hôi, giảm #% HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (110, 0, 'Dò pha lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (111, 0, 'Phân tâm');
insert into `optionitem` (`id`, `type`, `name`) VALUES (112, 0, 'Giảm #% khi mua Avatar hoặc Cải trang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (113, 0, 'Ném cho Sói Hẹc Quyn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (114, 0, '+#% TĐ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (115, 0, 'Biến cà rốt');
insert into `optionitem` (`id`, `type`, `name`) VALUES (116, 0, 'Kháng TDHS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (117, 0, 'Đẹp +#% SĐ cho mình và người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (118, 0, 'Tới ngay mục tiêu và gây choáng trong # mili giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (119, 0, 'Gây mù xung quanh trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (120, 0, 'Ra đòn sau # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (121, 0, 'Ru ngủ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (122, 0, 'Bảo vệ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (123, 0, 'Trói gô mục tiêu trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (124, 0, 'Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (125, 0, 'Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (126, 0, 'Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (127, 0, 'Set Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (128, 0, 'Set Kaioken');
insert into `optionitem` (`id`, `type`, `name`) VALUES (129, 0, 'Set  Sôngôku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (130, 0, 'Set Picolo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (131, 0, 'Set Ốc tiêu');
insert into `optionitem` (`id`, `type`, `name`) VALUES (132, 0, 'Set Pikkoro Daimao');
insert into `optionitem` (`id`, `type`, `name`) VALUES (133, 0, 'Set Kakarot');
insert into `optionitem` (`id`, `type`, `name`) VALUES (134, 0, 'Set Ca Đíc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (135, 0, 'Set Nappa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (136, 0, '$(5 món +100% sát thương đấm Galick)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (137, 0, '$(5 món x5 thời gian hóa khỉ)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (138, 0, '$(5 món +100% HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (139, 0, '$(5 món x2 thời gian chói mắt)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (140, 0, '$(5 món +100% sát thương Kaioken)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (141, 0, '$(5 món +100% sát thương Kamejoko)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (142, 0, '$(5 món +100% KI)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (143, 0, '$(5 món +100% sát thương Liên hoàn)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (144, 0, '$(5 món +100% sát thương Đẻ Trứng)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (145, 0, '$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (146, 0, '$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (147, 0, '+#% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (148, 0, '+#% tốc độ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (149, 0, '(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (150, 0, '(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (151, 0, '$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (152, 0, '$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (153, 0, '#% tỉ lệ phát nổ sau khi chết');
insert into `optionitem` (`id`, `type`, `name`) VALUES (154, 0, 'Không thể bán lại cho người khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (155, 0, 'Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (156, 0, 'Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (157, 0, 'Giảm #% mọi sát thương khi KI dưới 20%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (158, 0, 'Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (159, 0, 'x# sức đánh đòn chưởng cơ bản mỗi phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (160, 0, '+#% TN, SM cho đệ tử khi sư phụ mặc cải trang này');
insert into `optionitem` (`id`, `type`, `name`) VALUES (161, 0, 'Thêm # ngọc mỗi ngày khi đánh quái.');
insert into `optionitem` (`id`, `type`, `name`) VALUES (162, 0, 'Cute hồi #% KI/s bản thân và xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (163, 0, 'Biến người xung quanh thành Bí Ngô');
insert into `optionitem` (`id`, `type`, `name`) VALUES (164, 0, 'Đổi bằng # điểm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (165, 0, 'Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (166, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (167, 0, 'Tạo không khí lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (168, 0, 'Hấp thụ sức mạnh rồi bộc phá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (169, 0, 'Cơ hội hạ độc đối thủ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (170, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide');
insert into `optionitem` (`id`, `type`, `name`) VALUES (171, 0, 'Số lượng #K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (172, 0, '#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (173, 0, 'Phục hồi #% HP và KI cho đồng đội');
insert into `optionitem` (`id`, `type`, `name`) VALUES (174, 0, 'Sự kiện năm #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (175, 0, 'Giảm #% thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (176, 0, '$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (177, 0, '$(Tối đa +2% tất cả khi ở gần Mabư mập)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (178, 0, 'KI+#%/10s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (179, 0, '+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost');
insert into `optionitem` (`id`, `type`, `name`) VALUES (180, 0, '+#% sức đánh khi ở gần Cải Trang Black Gohan Rose');
insert into `optionitem` (`id`, `type`, `name`) VALUES (181, 0, 'Dịch chuyển tức thời +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (182, 0, '+#% sát thương đệ từ trứng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (183, 0, 'Giảm #% thời gian hồi Khiên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (184, 0, '+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (185, 0, '+# giờ sử dụng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (186, 0, 'Biến mọi người xung quanh thành kẹo mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (187, 0, 'Giảm # giây thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (188, 0, 'Set Siêu Xên Chủng Nthev');
insert into `optionitem` (`id`, `type`, `name`) VALUES (189, 0, '$(5 món +50% Giảm Chịu Sát Thương và HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (190, 0, 'Ngọc hóa Lv#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (191, 0, 'Đã # lần ép ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (192, 0, 'SET WORLDCUP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (193, 0, '$(Tăng 10%HP,KI và 20% sức đánh chí mạng khi mặc 2 món WORLDCUP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (194, 0, 'Pet Follow');
insert into `optionitem` (`id`, `type`, `name`) VALUES (195, 0, 'Chí Tôn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (196, 0, 'Option6');
insert into `optionitem` (`id`, `type`, `name`) VALUES (197, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (198, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (199, 0, 'Chỉ dành cho đệ tử');
insert into `optionitem` (`id`, `type`, `name`) VALUES (200, 0, 'Được phép tiến vào Dị Giới và mọi map');
insert into `optionitem` (`id`, `type`, `name`) VALUES (201, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (202, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (203, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (204, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (205, 0, 'Đã Dùng # Lần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (206, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (207, 0, 'Cải Trang Sự Kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (208, 0, 'Đồ rơi từ Quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (209, 0, 'Đồ rơi từ Boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (210, 0, 'Thẻ SooMe');
insert into `optionitem` (`id`, `type`, `name`) VALUES (211, 0, 'Anh Béo Đẹp Zai');
insert into `optionitem` (`id`, `type`, `name`) VALUES (0, 0, 'Tấn công+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (1, 0, 'Thời gian sử dụng # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (2, 0, 'HP, KI+#000');
insert into `optionitem` (`id`, `type`, `name`) VALUES (3, 0, 'Vô hiệu và biến #% sát thương chưởng thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (4, 0, 'Hồi phục #% KI khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (5, 0, '+#% sát thương chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (6, 0, 'HP+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (7, 0, 'KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (8, 0, 'Hút #% HP, KI xung quanh mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (9, 0, 'Hiệu lực trong # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (10, 0, 'Chính xác: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (11, 0, 'Công đức +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (12, 0, 'Số lần sử dụng còn lại +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (13, 0, 'Số yêu quái đã hạ +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (14, 0, 'Chí mạng+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (15, 0, 'Phản đòn cận chiến+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (16, 0, 'Tốc độ di chuyển+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (17, 0, 'Né đòn: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (18, 0, 'Chính xác: +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (19, 0, 'Tấn công+#% khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (20, 0, 'PIN #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (21, 0, 'Yêu cầu sức mạnh # tỉ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (22, 0, 'HP+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (23, 0, 'KI+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (24, 0, 'Làm tăng trọng lực, gây chậm mọi người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (25, 0, 'Tàng hình mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (26, 0, 'Hóa đá mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (27, 0, '+# HP/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (28, 0, '+# KI/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (29, 0, 'Biến Sôcôla mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (30, 0, 'Không thể giao dịch');
insert into `optionitem` (`id`, `type`, `name`) VALUES (31, 0, 'Số lượng #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (32, 0, 'Không bị hóa Xương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (33, 0, 'Dịch chuyển tức thời');
insert into `optionitem` (`id`, `type`, `name`) VALUES (34, 0, 'Tinh ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (35, 0, 'Nguyệt ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (36, 0, 'Nhật ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (37, 0, 'Số lần đã ký gửi #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (38, 0, 'Chỉ có tác dụng khi hợp thể');
insert into `optionitem` (`id`, `type`, `name`) VALUES (39, 0, '<Cập nhật bản mới để xem>');
insert into `optionitem` (`id`, `type`, `name`) VALUES (40, 0, 'Siêu cải trang # đá ngũ sắc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (41, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (42, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (43, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (44, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (45, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (46, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (47, 0, 'Giáp+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (48, 0, 'HP, KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (49, 0, 'Tấn công+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (50, 0, 'Sức đánh+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (51, 0, 'Sôn Gô Ku ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (52, 0, 'Ca Đic siêu ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (53, 0, 'Broly');
insert into `optionitem` (`id`, `type`, `name`) VALUES (54, 0, 'Mr. Santa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (55, 0, 'Broly ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (56, 0, 'Ca Lích');
insert into `optionitem` (`id`, `type`, `name`) VALUES (57, 0, 'Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (58, 0, 'Pic');
insert into `optionitem` (`id`, `type`, `name`) VALUES (59, 0, 'Siêu na mếc #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (60, 0, 'Sôn Gô Tên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (61, 0, 'Sôn Gô Ku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (62, 0, 'Phục hồi thể lực #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (63, 0, 'Còn lại # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (64, 0, 'Còn lại # giờ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (65, 0, 'Còn lại # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (66, 0, 'Chưa có');
insert into `optionitem` (`id`, `type`, `name`) VALUES (67, 0, 'Dùng nâng cấp găng tay');
insert into `optionitem` (`id`, `type`, `name`) VALUES (68, 0, 'Dùng để nâng cấp áo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (69, 0, 'Dùng để nâng cấp quần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (70, 0, 'Dùng để nâng cấp giày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (71, 0, 'HS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (72, 0, 'Cấp #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (73, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (74, 0, 'Dùng để ép thành đá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (75, 0, 'Dùng để làm phép');
insert into `optionitem` (`id`, `type`, `name`) VALUES (76, 0, 'Vip');
insert into `optionitem` (`id`, `type`, `name`) VALUES (77, 0, 'HP+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (78, 0, 'Sức hủy diệt+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (79, 0, 'Đệ tử #% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (80, 0, 'HP+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (81, 0, 'KI+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (82, 0, 'Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (83, 0, 'Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (84, 0, 'Dùng để bay không tốn KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (85, 0, 'Dùng để bay và phục hồi KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (86, 0, 'Ký gửi vàng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (87, 0, 'Ký gửi ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (88, 0, 'Cộng #% exp khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (89, 0, 'Dùng để bay và phục hồi HP, KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (90, 0, 'Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (91, 0, 'Mở ra để nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (92, 0, 'Chúc tết bang hội và mọi người kèm theo pháo hoa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (93, 0, 'HSD # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (94, 0, 'Giáp #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (95, 0, 'Biến #% tấn công thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (96, 0, 'Biến #% tấn công thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (97, 0, 'Phản #% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (98, 0, 'Xuyên giáp #% chưởng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (99, 0, 'Xuyên giáp #% cận chiến');
insert into `optionitem` (`id`, `type`, `name`) VALUES (100, 0, '+#% vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (101, 0, '+#% TN,SM');
insert into `optionitem` (`id`, `type`, `name`) VALUES (102, 0, '# Sao Pha Lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (103, 0, 'KI +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (104, 0, 'Biến #% tấn công quái thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (105, 0, 'Vô hình khi không đánh quái và boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (106, 0, 'Không ảnh hưởng bởi cái lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (107, 0, '# Sao Pha Lê (Chưa ép)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (108, 0, '#% Né đòn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (109, 0, 'Hôi, giảm #% HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (110, 0, 'Dò pha lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (111, 0, 'Phân tâm');
insert into `optionitem` (`id`, `type`, `name`) VALUES (112, 0, 'Giảm #% khi mua Avatar hoặc Cải trang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (113, 0, 'Ném cho Sói Hẹc Quyn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (114, 0, '+#% TĐ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (115, 0, 'Biến cà rốt');
insert into `optionitem` (`id`, `type`, `name`) VALUES (116, 0, 'Kháng TDHS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (117, 0, 'Đẹp +#% SĐ cho mình và người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (118, 0, 'Tới ngay mục tiêu và gây choáng trong # mili giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (119, 0, 'Gây mù xung quanh trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (120, 0, 'Ra đòn sau # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (121, 0, 'Ru ngủ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (122, 0, 'Bảo vệ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (123, 0, 'Trói gô mục tiêu trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (124, 0, 'Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (125, 0, 'Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (126, 0, 'Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (127, 0, 'Set Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (128, 0, 'Set Kaioken');
insert into `optionitem` (`id`, `type`, `name`) VALUES (129, 0, 'Set  Sôngôku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (130, 0, 'Set Picolo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (131, 0, 'Set Ốc tiêu');
insert into `optionitem` (`id`, `type`, `name`) VALUES (132, 0, 'Set Pikkoro Daimao');
insert into `optionitem` (`id`, `type`, `name`) VALUES (133, 0, 'Set Kakarot');
insert into `optionitem` (`id`, `type`, `name`) VALUES (134, 0, 'Set Ca Đíc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (135, 0, 'Set Nappa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (136, 0, '$(5 món +100% sát thương đấm Galick)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (137, 0, '$(5 món x5 thời gian hóa khỉ)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (138, 0, '$(5 món +100% HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (139, 0, '$(5 món x2 thời gian chói mắt)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (140, 0, '$(5 món +100% sát thương Kaioken)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (141, 0, '$(5 món +100% sát thương Kamejoko)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (142, 0, '$(5 món +100% KI)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (143, 0, '$(5 món +100% sát thương Liên hoàn)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (144, 0, '$(5 món +100% sát thương Đẻ Trứng)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (145, 0, '$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (146, 0, '$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (147, 0, '+#% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (148, 0, '+#% tốc độ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (149, 0, '(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (150, 0, '(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (151, 0, '$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (152, 0, '$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (153, 0, '#% tỉ lệ phát nổ sau khi chết');
insert into `optionitem` (`id`, `type`, `name`) VALUES (154, 0, 'Không thể bán lại cho người khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (155, 0, 'Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (156, 0, 'Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (157, 0, 'Giảm #% mọi sát thương khi KI dưới 20%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (158, 0, 'Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (159, 0, 'x# sức đánh đòn chưởng cơ bản mỗi phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (160, 0, '+#% TN, SM cho đệ tử khi sư phụ mặc cải trang này');
insert into `optionitem` (`id`, `type`, `name`) VALUES (161, 0, 'Thêm # ngọc mỗi ngày khi đánh quái.');
insert into `optionitem` (`id`, `type`, `name`) VALUES (162, 0, 'Cute hồi #% KI/s bản thân và xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (163, 0, 'Biến người xung quanh thành Bí Ngô');
insert into `optionitem` (`id`, `type`, `name`) VALUES (164, 0, 'Đổi bằng # điểm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (165, 0, 'Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (166, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (167, 0, 'Tạo không khí lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (168, 0, 'Hấp thụ sức mạnh rồi bộc phá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (169, 0, 'Cơ hội hạ độc đối thủ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (170, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide');
insert into `optionitem` (`id`, `type`, `name`) VALUES (171, 0, 'Số lượng #K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (172, 0, '#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (173, 0, 'Phục hồi #% HP và KI cho đồng đội');
insert into `optionitem` (`id`, `type`, `name`) VALUES (174, 0, 'Sự kiện năm #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (175, 0, 'Giảm #% thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (176, 0, '$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (177, 0, '$(Tối đa +2% tất cả khi ở gần Mabư mập)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (178, 0, 'KI+#%/10s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (179, 0, '+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost');
insert into `optionitem` (`id`, `type`, `name`) VALUES (180, 0, '+#% sức đánh khi ở gần Cải Trang Black Gohan Rose');
insert into `optionitem` (`id`, `type`, `name`) VALUES (181, 0, 'Dịch chuyển tức thời +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (182, 0, '+#% sát thương đệ từ trứng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (183, 0, 'Giảm #% thời gian hồi Khiên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (184, 0, '+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (185, 0, '+# giờ sử dụng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (186, 0, 'Biến mọi người xung quanh thành kẹo mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (187, 0, 'Giảm # giây thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (188, 0, 'Set Siêu Xên Chủng Nthev');
insert into `optionitem` (`id`, `type`, `name`) VALUES (189, 0, '$(5 món +50% Giảm Chịu Sát Thương và HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (190, 0, 'Ngọc hóa Lv#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (191, 0, 'Đã # lần ép ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (192, 0, 'SET WORLDCUP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (193, 0, '$(Tăng 10%HP,KI và 20% sức đánh chí mạng khi mặc 2 món WORLDCUP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (194, 0, 'Pet Follow');
insert into `optionitem` (`id`, `type`, `name`) VALUES (195, 0, 'Chí Tôn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (196, 0, 'Option6');
insert into `optionitem` (`id`, `type`, `name`) VALUES (197, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (198, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (199, 0, 'Chỉ dành cho đệ tử');
insert into `optionitem` (`id`, `type`, `name`) VALUES (200, 0, 'Được phép tiến vào Dị Giới và mọi map');
insert into `optionitem` (`id`, `type`, `name`) VALUES (201, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (202, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (203, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (204, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (205, 0, 'Đã Dùng # Lần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (206, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (207, 0, 'Cải Trang Sự Kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (208, 0, 'Đồ rơi từ Quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (209, 0, 'Đồ rơi từ Boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (210, 0, 'Thẻ SooMe');
insert into `optionitem` (`id`, `type`, `name`) VALUES (211, 0, 'Anh Béo Đẹp Zai');
insert into `optionitem` (`id`, `type`, `name`) VALUES (0, 0, 'Tấn công+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (1, 0, 'Thời gian sử dụng # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (2, 0, 'HP, KI+#000');
insert into `optionitem` (`id`, `type`, `name`) VALUES (3, 0, 'Vô hiệu và biến #% sát thương chưởng thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (4, 0, 'Hồi phục #% KI khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (5, 0, '+#% sát thương chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (6, 0, 'HP+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (7, 0, 'KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (8, 0, 'Hút #% HP, KI xung quanh mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (9, 0, 'Hiệu lực trong # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (10, 0, 'Chính xác: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (11, 0, 'Công đức +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (12, 0, 'Số lần sử dụng còn lại +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (13, 0, 'Số yêu quái đã hạ +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (14, 0, 'Chí mạng+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (15, 0, 'Phản đòn cận chiến+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (16, 0, 'Tốc độ di chuyển+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (17, 0, 'Né đòn: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (18, 0, 'Chính xác: +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (19, 0, 'Tấn công+#% khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (20, 0, 'PIN #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (21, 0, 'Yêu cầu sức mạnh # tỉ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (22, 0, 'HP+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (23, 0, 'KI+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (24, 0, 'Làm tăng trọng lực, gây chậm mọi người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (25, 0, 'Tàng hình mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (26, 0, 'Hóa đá mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (27, 0, '+# HP/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (28, 0, '+# KI/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (29, 0, 'Biến Sôcôla mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (30, 0, 'Không thể giao dịch');
insert into `optionitem` (`id`, `type`, `name`) VALUES (31, 0, 'Số lượng #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (32, 0, 'Không bị hóa Xương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (33, 0, 'Dịch chuyển tức thời');
insert into `optionitem` (`id`, `type`, `name`) VALUES (34, 0, 'Tinh ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (35, 0, 'Nguyệt ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (36, 0, 'Nhật ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (37, 0, 'Số lần đã ký gửi #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (38, 0, 'Chỉ có tác dụng khi hợp thể');
insert into `optionitem` (`id`, `type`, `name`) VALUES (39, 0, '<Cập nhật bản mới để xem>');
insert into `optionitem` (`id`, `type`, `name`) VALUES (40, 0, 'Siêu cải trang # đá ngũ sắc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (41, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (42, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (43, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (44, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (45, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (46, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (47, 0, 'Giáp+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (48, 0, 'HP, KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (49, 0, 'Tấn công+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (50, 0, 'Sức đánh+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (51, 0, 'Sôn Gô Ku ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (52, 0, 'Ca Đic siêu ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (53, 0, 'Broly');
insert into `optionitem` (`id`, `type`, `name`) VALUES (54, 0, 'Mr. Santa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (55, 0, 'Broly ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (56, 0, 'Ca Lích');
insert into `optionitem` (`id`, `type`, `name`) VALUES (57, 0, 'Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (58, 0, 'Pic');
insert into `optionitem` (`id`, `type`, `name`) VALUES (59, 0, 'Siêu na mếc #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (60, 0, 'Sôn Gô Tên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (61, 0, 'Sôn Gô Ku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (62, 0, 'Phục hồi thể lực #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (63, 0, 'Còn lại # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (64, 0, 'Còn lại # giờ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (65, 0, 'Còn lại # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (66, 0, 'Chưa có');
insert into `optionitem` (`id`, `type`, `name`) VALUES (67, 0, 'Dùng nâng cấp găng tay');
insert into `optionitem` (`id`, `type`, `name`) VALUES (68, 0, 'Dùng để nâng cấp áo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (69, 0, 'Dùng để nâng cấp quần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (70, 0, 'Dùng để nâng cấp giày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (71, 0, 'HS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (72, 0, 'Cấp #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (73, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (74, 0, 'Dùng để ép thành đá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (75, 0, 'Dùng để làm phép');
insert into `optionitem` (`id`, `type`, `name`) VALUES (76, 0, 'Vip');
insert into `optionitem` (`id`, `type`, `name`) VALUES (77, 0, 'HP+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (78, 0, 'Sức hủy diệt+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (79, 0, 'Đệ tử #% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (80, 0, 'HP+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (81, 0, 'KI+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (82, 0, 'Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (83, 0, 'Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (84, 0, 'Dùng để bay không tốn KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (85, 0, 'Dùng để bay và phục hồi KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (86, 0, 'Ký gửi vàng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (87, 0, 'Ký gửi ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (88, 0, 'Cộng #% exp khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (89, 0, 'Dùng để bay và phục hồi HP, KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (90, 0, 'Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (91, 0, 'Mở ra để nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (92, 0, 'Chúc tết bang hội và mọi người kèm theo pháo hoa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (93, 0, 'HSD # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (94, 0, 'Giáp #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (95, 0, 'Biến #% tấn công thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (96, 0, 'Biến #% tấn công thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (97, 0, 'Phản #% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (98, 0, 'Xuyên giáp #% chưởng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (99, 0, 'Xuyên giáp #% cận chiến');
insert into `optionitem` (`id`, `type`, `name`) VALUES (100, 0, '+#% vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (101, 0, '+#% TN,SM');
insert into `optionitem` (`id`, `type`, `name`) VALUES (102, 0, '# Sao Pha Lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (103, 0, 'KI +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (104, 0, 'Biến #% tấn công quái thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (105, 0, 'Vô hình khi không đánh quái và boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (106, 0, 'Không ảnh hưởng bởi cái lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (107, 0, '# Sao Pha Lê (Chưa ép)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (108, 0, '#% Né đòn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (109, 0, 'Hôi, giảm #% HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (110, 0, 'Dò pha lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (111, 0, 'Phân tâm');
insert into `optionitem` (`id`, `type`, `name`) VALUES (112, 0, 'Giảm #% khi mua Avatar hoặc Cải trang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (113, 0, 'Ném cho Sói Hẹc Quyn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (114, 0, '+#% TĐ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (115, 0, 'Biến cà rốt');
insert into `optionitem` (`id`, `type`, `name`) VALUES (116, 0, 'Kháng TDHS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (117, 0, 'Đẹp +#% SĐ cho mình và người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (118, 0, 'Tới ngay mục tiêu và gây choáng trong # mili giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (119, 0, 'Gây mù xung quanh trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (120, 0, 'Ra đòn sau # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (121, 0, 'Ru ngủ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (122, 0, 'Bảo vệ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (123, 0, 'Trói gô mục tiêu trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (124, 0, 'Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (125, 0, 'Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (126, 0, 'Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (127, 0, 'Set Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (128, 0, 'Set Kaioken');
insert into `optionitem` (`id`, `type`, `name`) VALUES (129, 0, 'Set  Sôngôku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (130, 0, 'Set Picolo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (131, 0, 'Set Ốc tiêu');
insert into `optionitem` (`id`, `type`, `name`) VALUES (132, 0, 'Set Pikkoro Daimao');
insert into `optionitem` (`id`, `type`, `name`) VALUES (133, 0, 'Set Kakarot');
insert into `optionitem` (`id`, `type`, `name`) VALUES (134, 0, 'Set Ca Đíc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (135, 0, 'Set Nappa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (136, 0, '$(5 món +100% sát thương đấm Galick)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (137, 0, '$(5 món x5 thời gian hóa khỉ)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (138, 0, '$(5 món +100% HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (139, 0, '$(5 món x2 thời gian chói mắt)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (140, 0, '$(5 món +100% sát thương Kaioken)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (141, 0, '$(5 món +100% sát thương Kamejoko)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (142, 0, '$(5 món +100% KI)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (143, 0, '$(5 món +100% sát thương Liên hoàn)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (144, 0, '$(5 món +100% sát thương Đẻ Trứng)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (145, 0, '$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (146, 0, '$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (147, 0, '+#% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (148, 0, '+#% tốc độ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (149, 0, '(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (150, 0, '(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (151, 0, '$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (152, 0, '$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (153, 0, '#% tỉ lệ phát nổ sau khi chết');
insert into `optionitem` (`id`, `type`, `name`) VALUES (154, 0, 'Không thể bán lại cho người khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (155, 0, 'Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (156, 0, 'Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (157, 0, 'Giảm #% mọi sát thương khi KI dưới 20%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (158, 0, 'Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (159, 0, 'x# sức đánh đòn chưởng cơ bản mỗi phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (160, 0, '+#% TN, SM cho đệ tử khi sư phụ mặc cải trang này');
insert into `optionitem` (`id`, `type`, `name`) VALUES (161, 0, 'Thêm # ngọc mỗi ngày khi đánh quái.');
insert into `optionitem` (`id`, `type`, `name`) VALUES (162, 0, 'Cute hồi #% KI/s bản thân và xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (163, 0, 'Biến người xung quanh thành Bí Ngô');
insert into `optionitem` (`id`, `type`, `name`) VALUES (164, 0, 'Đổi bằng # điểm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (165, 0, 'Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (166, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (167, 0, 'Tạo không khí lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (168, 0, 'Hấp thụ sức mạnh rồi bộc phá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (169, 0, 'Cơ hội hạ độc đối thủ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (170, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide');
insert into `optionitem` (`id`, `type`, `name`) VALUES (171, 0, 'Số lượng #K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (172, 0, '#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (173, 0, 'Phục hồi #% HP và KI cho đồng đội');
insert into `optionitem` (`id`, `type`, `name`) VALUES (174, 0, 'Sự kiện năm #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (175, 0, 'Giảm #% thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (176, 0, '$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (177, 0, '$(Tối đa +2% tất cả khi ở gần Mabư mập)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (178, 0, 'KI+#%/10s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (179, 0, '+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost');
insert into `optionitem` (`id`, `type`, `name`) VALUES (180, 0, '+#% sức đánh khi ở gần Cải Trang Black Gohan Rose');
insert into `optionitem` (`id`, `type`, `name`) VALUES (181, 0, 'Dịch chuyển tức thời +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (182, 0, '+#% sát thương đệ từ trứng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (183, 0, 'Giảm #% thời gian hồi Khiên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (184, 0, '+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (185, 0, '+# giờ sử dụng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (186, 0, 'Biến mọi người xung quanh thành kẹo mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (187, 0, 'Giảm # giây thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (188, 0, 'Set Siêu Xên Chủng Nthev');
insert into `optionitem` (`id`, `type`, `name`) VALUES (189, 0, '$(5 món +50% Giảm Chịu Sát Thương và HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (190, 0, 'Ngọc hóa Lv#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (191, 0, 'Đã # lần ép ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (192, 0, 'SET WORLDCUP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (193, 0, '$(Tăng 10%HP,KI và 20% sức đánh chí mạng khi mặc 2 món WORLDCUP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (194, 0, 'Pet Follow');
insert into `optionitem` (`id`, `type`, `name`) VALUES (195, 0, 'Chí Tôn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (196, 0, 'Option6');
insert into `optionitem` (`id`, `type`, `name`) VALUES (197, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (198, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (199, 0, 'Chỉ dành cho đệ tử');
insert into `optionitem` (`id`, `type`, `name`) VALUES (200, 0, 'Được phép tiến vào Dị Giới và mọi map');
insert into `optionitem` (`id`, `type`, `name`) VALUES (201, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (202, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (203, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (204, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (205, 0, 'Đã Dùng # Lần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (206, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (207, 0, 'Cải Trang Sự Kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (208, 0, 'Đồ rơi từ Quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (209, 0, 'Đồ rơi từ Boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (210, 0, 'Thẻ SooMe');
insert into `optionitem` (`id`, `type`, `name`) VALUES (211, 0, 'Anh Béo Đẹp Zai');
insert into `optionitem` (`id`, `type`, `name`) VALUES (0, 0, 'Tấn công+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (1, 0, 'Thời gian sử dụng # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (2, 0, 'HP, KI+#000');
insert into `optionitem` (`id`, `type`, `name`) VALUES (3, 0, 'Vô hiệu và biến #% sát thương chưởng thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (4, 0, 'Hồi phục #% KI khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (5, 0, '+#% sát thương chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (6, 0, 'HP+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (7, 0, 'KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (8, 0, 'Hút #% HP, KI xung quanh mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (9, 0, 'Hiệu lực trong # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (10, 0, 'Chính xác: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (11, 0, 'Công đức +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (12, 0, 'Số lần sử dụng còn lại +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (13, 0, 'Số yêu quái đã hạ +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (14, 0, 'Chí mạng+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (15, 0, 'Phản đòn cận chiến+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (16, 0, 'Tốc độ di chuyển+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (17, 0, 'Né đòn: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (18, 0, 'Chính xác: +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (19, 0, 'Tấn công+#% khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (20, 0, 'PIN #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (21, 0, 'Yêu cầu sức mạnh # tỉ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (22, 0, 'HP+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (23, 0, 'KI+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (24, 0, 'Làm tăng trọng lực, gây chậm mọi người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (25, 0, 'Tàng hình mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (26, 0, 'Hóa đá mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (27, 0, '+# HP/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (28, 0, '+# KI/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (29, 0, 'Biến Sôcôla mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (30, 0, 'Không thể giao dịch');
insert into `optionitem` (`id`, `type`, `name`) VALUES (31, 0, 'Số lượng #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (32, 0, 'Không bị hóa Xương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (33, 0, 'Dịch chuyển tức thời');
insert into `optionitem` (`id`, `type`, `name`) VALUES (34, 0, 'Tinh ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (35, 0, 'Nguyệt ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (36, 0, 'Nhật ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (37, 0, 'Số lần đã ký gửi #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (38, 0, 'Chỉ có tác dụng khi hợp thể');
insert into `optionitem` (`id`, `type`, `name`) VALUES (39, 0, '<Cập nhật bản mới để xem>');
insert into `optionitem` (`id`, `type`, `name`) VALUES (40, 0, 'Siêu cải trang # đá ngũ sắc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (41, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (42, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (43, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (44, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (45, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (46, 0, '(+16)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (47, 0, 'Giáp+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (48, 0, 'HP, KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (49, 0, 'Tấn công+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (50, 0, 'Sức đánh+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (51, 0, 'Sôn Gô Ku ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (52, 0, 'Ca Đic siêu ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (53, 0, 'Broly');
insert into `optionitem` (`id`, `type`, `name`) VALUES (54, 0, 'Mr. Santa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (55, 0, 'Broly ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (56, 0, 'Ca Lích');
insert into `optionitem` (`id`, `type`, `name`) VALUES (57, 0, 'Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (58, 0, 'Pic');
insert into `optionitem` (`id`, `type`, `name`) VALUES (59, 0, 'Siêu na mếc #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (60, 0, 'Sôn Gô Tên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (61, 0, 'Sôn Gô Ku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (62, 0, 'Phục hồi thể lực #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (63, 0, 'Còn lại # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (64, 0, 'Còn lại # giờ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (65, 0, 'Còn lại # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (66, 0, 'Chưa có');
insert into `optionitem` (`id`, `type`, `name`) VALUES (67, 0, 'Dùng nâng cấp găng tay');
insert into `optionitem` (`id`, `type`, `name`) VALUES (68, 0, 'Dùng để nâng cấp áo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (69, 0, 'Dùng để nâng cấp quần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (70, 0, 'Dùng để nâng cấp giày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (71, 0, 'HS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (72, 0, 'Cấp #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (73, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (74, 0, 'Dùng để ép thành đá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (75, 0, 'Dùng để làm phép');
insert into `optionitem` (`id`, `type`, `name`) VALUES (76, 0, 'Vip');
insert into `optionitem` (`id`, `type`, `name`) VALUES (77, 0, 'HP+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (78, 0, 'Sức hủy diệt+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (79, 0, 'Đệ tử #% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (80, 0, 'HP+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (81, 0, 'KI+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (82, 0, 'Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (83, 0, 'Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (84, 0, 'Dùng để bay không tốn KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (85, 0, 'Dùng để bay và phục hồi KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (86, 0, 'Ký gửi vàng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (87, 0, 'Ký gửi ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (88, 0, 'Cộng #% exp khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (89, 0, 'Dùng để bay và phục hồi HP, KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (90, 0, 'Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (91, 0, 'Mở ra để nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (92, 0, 'Chúc tết bang hội và mọi người kèm theo pháo hoa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (93, 0, 'HSD # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (94, 0, 'Giáp #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (95, 0, 'Biến #% tấn công thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (96, 0, 'Biến #% tấn công thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (97, 0, 'Phản #% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (98, 0, 'Xuyên giáp #% chưởng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (99, 0, 'Xuyên giáp #% cận chiến');
insert into `optionitem` (`id`, `type`, `name`) VALUES (100, 0, '+#% vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (101, 0, '+#% TN,SM');
insert into `optionitem` (`id`, `type`, `name`) VALUES (102, 0, '# Sao Pha Lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (103, 0, 'KI +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (104, 0, 'Biến #% tấn công quái thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (105, 0, 'Vô hình khi không đánh quái và boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (106, 0, 'Không ảnh hưởng bởi cái lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (107, 0, '# Sao Pha Lê (Chưa ép)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (108, 0, '#% Né đòn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (109, 0, 'Hôi, giảm #% HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (110, 0, 'Dò pha lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (111, 0, 'Phân tâm');
insert into `optionitem` (`id`, `type`, `name`) VALUES (112, 0, 'Giảm #% khi mua Avatar hoặc Cải trang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (113, 0, 'Ném cho Sói Hẹc Quyn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (114, 0, '+#% TĐ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (115, 0, 'Biến cà rốt');
insert into `optionitem` (`id`, `type`, `name`) VALUES (116, 0, 'Kháng TDHS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (117, 0, 'Đẹp +#% SĐ cho mình và người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (118, 0, 'Tới ngay mục tiêu và gây choáng trong # mili giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (119, 0, 'Gây mù xung quanh trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (120, 0, 'Ra đòn sau # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (121, 0, 'Ru ngủ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (122, 0, 'Bảo vệ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (123, 0, 'Trói gô mục tiêu trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (124, 0, 'Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (125, 0, 'Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (126, 0, 'Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (127, 0, 'Set Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (128, 0, 'Set Kaioken');
insert into `optionitem` (`id`, `type`, `name`) VALUES (129, 0, 'Set  Sôngôku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (130, 0, 'Set Picolo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (131, 0, 'Set Ốc tiêu');
insert into `optionitem` (`id`, `type`, `name`) VALUES (132, 0, 'Set Pikkoro Daimao');
insert into `optionitem` (`id`, `type`, `name`) VALUES (133, 0, 'Set Kakarot');
insert into `optionitem` (`id`, `type`, `name`) VALUES (134, 0, 'Set Ca Đíc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (135, 0, 'Set Nappa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (136, 0, '$(5 món +100% sát thương đấm Galick)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (137, 0, '$(5 món x5 thời gian hóa khỉ)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (138, 0, '$(5 món +100% HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (139, 0, '$(5 món x2 thời gian chói mắt)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (140, 0, '$(5 món +100% sát thương Kaioken)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (141, 0, '$(5 món +100% sát thương Kamejoko)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (142, 0, '$(5 món +100% KI)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (143, 0, '$(5 món +100% sát thương Liên hoàn)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (144, 0, '$(5 món +100% sát thương Đẻ Trứng)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (145, 0, '$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (146, 0, '$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (147, 0, '+#% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (148, 0, '+#% tốc độ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (149, 0, '(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (150, 0, '(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (151, 0, '$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (152, 0, '$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (153, 0, '#% tỉ lệ phát nổ sau khi chết');
insert into `optionitem` (`id`, `type`, `name`) VALUES (154, 0, 'Không thể bán lại cho người khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (155, 0, 'Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (156, 0, 'Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (157, 0, 'Giảm #% mọi sát thương khi KI dưới 20%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (158, 0, 'Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (159, 0, 'x# sức đánh đòn chưởng cơ bản mỗi phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (160, 0, '+#% TN, SM cho đệ tử khi sư phụ mặc cải trang này');
insert into `optionitem` (`id`, `type`, `name`) VALUES (161, 0, 'Thêm # ngọc mỗi ngày khi đánh quái.');
insert into `optionitem` (`id`, `type`, `name`) VALUES (162, 0, 'Cute hồi #% KI/s bản thân và xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (163, 0, 'Biến người xung quanh thành Bí Ngô');
insert into `optionitem` (`id`, `type`, `name`) VALUES (164, 0, 'Đổi bằng # điểm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (165, 0, 'Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (166, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (167, 0, 'Tạo không khí lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (168, 0, 'Hấp thụ sức mạnh rồi bộc phá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (169, 0, 'Cơ hội hạ độc đối thủ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (170, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide');
insert into `optionitem` (`id`, `type`, `name`) VALUES (171, 0, 'Số lượng #K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (172, 0, '#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (173, 0, 'Phục hồi #% HP và KI cho đồng đội');
insert into `optionitem` (`id`, `type`, `name`) VALUES (174, 0, 'Sự kiện năm #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (175, 0, 'Giảm #% thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (176, 0, '$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (177, 0, '$(Tối đa +2% tất cả khi ở gần Mabư mập)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (178, 0, 'KI+#%/10s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (179, 0, '+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost');
insert into `optionitem` (`id`, `type`, `name`) VALUES (180, 0, '+#% sức đánh khi ở gần Cải Trang Black Gohan Rose');
insert into `optionitem` (`id`, `type`, `name`) VALUES (181, 0, 'Dịch chuyển tức thời +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (182, 0, '+#% sát thương đệ từ trứng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (183, 0, 'Giảm #% thời gian hồi Khiên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (184, 0, '+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (185, 0, '+# giờ sử dụng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (186, 0, 'Biến mọi người xung quanh thành kẹo mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (187, 0, 'Giảm # giây thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (188, 0, 'Set Siêu Xên Chủng Nthev');
insert into `optionitem` (`id`, `type`, `name`) VALUES (189, 0, '$(5 món +50% Giảm Chịu Sát Thương và HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (190, 0, 'Ngọc hóa Lv#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (191, 0, 'Đã # lần ép ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (192, 0, 'SET WORLDCUP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (193, 0, '$(Tăng 10%HP,KI và 20% sức đánh chí mạng khi mặc 2 món WORLDCUP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (194, 0, 'Pet Follow');
insert into `optionitem` (`id`, `type`, `name`) VALUES (195, 0, 'Chí Tôn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (196, 0, 'Option6');
insert into `optionitem` (`id`, `type`, `name`) VALUES (197, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (198, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (199, 0, 'Chỉ dành cho đệ tử');
insert into `optionitem` (`id`, `type`, `name`) VALUES (200, 0, 'Được phép tiến vào Dị Giới và mọi map');
insert into `optionitem` (`id`, `type`, `name`) VALUES (201, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (202, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (203, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (204, 0, 'Option1');
insert into `optionitem` (`id`, `type`, `name`) VALUES (205, 0, 'Đã Dùng # Lần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (206, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (207, 0, 'Cải Trang Sự Kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (208, 0, 'Đồ rơi từ Quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (209, 0, 'Đồ rơi từ Boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (210, 0, 'Thẻ SooMe');
insert into `optionitem` (`id`, `type`, `name`) VALUES (211, 0, 'Anh Béo Đẹp Zai');
